#!/bin/bash

export RAILS_DATAROOT=$HOME/awesim/ContainerFillSim
export RAILS_DATABASE=$HOME/awesim/ContainerFillSim/db/production.sqlite3

mkdir -p `basename $RAILS_DATABASE`
mkdir -p $RAILS_DATAROOT
