#!/bin/bash

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SCRIPT=$(basename "${BASH_SOURCE[0]}")

# Make sure they supply an argument to this script
if [ -z "$1" ]; then
  echo "No deployment name specified"
  echo ""
  echo "Usage: ${SCRIPT} <deployment_name>"
  echo ""
  echo "This creates a deployment in ${HOME}/awesim_dev/deploy/<deployment_name>/"

  exit 1
fi

NAME=$1
DEPLOYMENT=${HOME}/awesim_dev/deploy/$NAME
GIT_DIR_NAME=$NAME.git
GIT_DIR=$DEPLOYMENT/$GIT_DIR_NAME
GIT_WORK_TREE=$DEPLOYMENT/$NAME

# error checking
if [ -e "$DEPLOYMENT" ]; then
  echo "ERROR - Path already exists: $DEPLOYMENT"
  echo ""
  exit 1
fi

# verify remote doesn't already exist
cd $DIR
git show-ref --verify --quiet refs/remotes/$NAME/master && echo "Remote $NAME already exists!" && exit 1


# setup deployment
mkdir -p $GIT_WORK_TREE

pushd $DEPLOYMENT
git init --bare $GIT_DIR_NAME
popd

cp osc_deploy.post-receive.sh $GIT_DIR/hooks/post-receive

# add remote
git remote add $NAME $GIT_DIR
echo "added remote: $NAME -> $GIT_DIR"
echo "push to the remote master branch deploy!"
echo ""
echo "  examples: git push $NAME master"
echo "            git push $NAME branch1:master"
