#!/bin/bash

# Directory where this project is hosted
DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SCRIPT=$(basename "${BASH_SOURCE[0]}")

# Make sure they supply an argument to this script
if [ -z "$1" ]; then
  echo "No rails path specified"
  echo ""
  echo "Usage: ${SCRIPT} <rails_path>"
  echo ""
  echo "This creates a symlink in ${HOME}/awesim_dev/<rails_path>"
  echo "  and sets all the approriate environment variables read"
  echo "  from the .env file"
  echo ""
  echo "For now it is recommended to name it rails1, rails2, ..."
  echo ""
  echo "WARNING: This will overwrite and current rails# directory"
  echo "  you may have in ~/awesim_dev"
  echo ""

  exit 1
fi

# New rails path
FINAL_DIR=${HOME}/awesim_dev/$1

# Make sure this path doesn't already exist
if [ -e "${FINAL_DIR}" ]; then
  echo "ERROR - Path already exists:"
  echo "  ${FINAL_DIR}"
  echo ""
  exit 1
fi

# Read in environment variables
source ${DIR}/.env.deployment

# Create symlink to this project
ln -s ${DIR} ${FINAL_DIR}

# Create directory to database if doesn't exist
# as well as a tmp/ and log/ path
mkdir -p "$(dirname "${RAILS_DATABASE}")"
mkdir -p "${RAILS_DATAROOT}/tmp" "${RAILS_DATAROOT}/log"

# Create database if it does not exist
if [ -e "${RAILS_DATABASE}" ]; then
  echo "Using the previous database found at:"
  echo "  ${RAILS_DATABASE}"
  echo ""
else
  cd ${DIR}
  RAILS_ENV=deployment rake db:setup
fi
