#!/bin/bash

if [ -e $HOME/.Xresources ]; then
  xrdb $HOME/.Xresources
fi
xsetroot -solid grey

export XSTARTUP_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
/usr/bin/fvwm -f ${XSTARTUP_DIR}/fvwm/fvwmrc &

. /etc/profile.d/lmod.sh
module load virtualgl/2.3
module load paraview/3.14.1

vglrun paraview --data=${DATAFILE}

vncserver -kill ${DISPLAY}
