#!/bin/bash

if [ -e $HOME/.Xresources ]; then
  xrdb $HOME/.Xresources
fi
xsetroot -solid grey

XDIR=${XSTARTUP_DIR} /usr/bin/fvwm -f ${XSTARTUP_DIR}/fvwm/fvwmrc &

. /etc/profile.d/lmod.sh
module load virtualgl/2.3
module load paraview/3.14.1

vglrun paraview --data=${DATAFILE}

vncserver -kill ${DISPLAY}
